
(function (root, factory) {
    var api = factory();

    if (typeof module !== "undefined" && module.exports) {
        module.exports = api;
    }

    if (typeof window !== "undefined") {
        window.PayloadGenData = api;
    }
}(typeof globalThis !== "undefined" ? globalThis : this, function () {
    "use strict";

    var CONFIG = { maxBlocks: 5, maxOutputLines: 5, defaultMtu: 1280, defaultHost: "google.com" };
    var STORAGE_KEYS = { theme: "payloadGen.theme", locale: "payloadGen.locale" };
    var THEMES = { light: "light", dark: "dark" };
    var DONATE_URL = "https://boosty.to/sketchystan1";
    var LATEST_QUIC_VERSION = 0x00000001;

    var CATEGORY_DEFS = [
        { id: "discovery", rank: 1, labelKey: "categoryDiscovery" },
        { id: "web", rank: 2, labelKey: "categoryWeb" },
        { id: "realtime", rank: 3, labelKey: "categoryRealtime" },
        { id: "iot", rank: 4, labelKey: "categoryIot" },
        { id: "infra", rank: 5, labelKey: "categoryInfra" },
        { id: "messaging", rank: 6, labelKey: "categoryMessaging" },
        { id: "p2p", rank: 7, labelKey: "categoryP2p" }
    ];

    var OPTION_SETS = {
        httpMethods: [{ value: "GET", labelKey: "httpMethodGet" }, { value: "HEAD", labelKey: "httpMethodHead" }, { value: "POST", labelKey: "httpMethodPost" }],
        sipActions: [{ value: "OPTIONS", labelKey: "sipActionOptions" }, { value: "REGISTER", labelKey: "sipActionRegister" }],
        coapMethods: [{ value: "GET", labelKey: "coapMethodGet" }, { value: "POST", labelKey: "coapMethodPost" }],
        tlsAlpn: [{ value: "http/1.1", labelKey: "tlsAlpnHttp11" }, { value: "h2", labelKey: "tlsAlpnH2" }],
        quicVersions: [{ value: "v1", labelKey: "quicVersionV1" }, { value: "v2", labelKey: "quicVersionV2" }],
        quicAwgLevels: [
            { value: "0", labelKey: "quicAwgLevel0" },
            { value: "1", labelKey: "quicAwgLevel1" },
            { value: "2", labelKey: "quicAwgLevel2" },
            { value: "3", labelKey: "quicAwgLevel3" },
            { value: "4", labelKey: "quicAwgLevel4" }
        ],
        browserProfiles: [{ value: "chrome", labelKey: "browserChrome" }, { value: "firefox", labelKey: "browserFirefox" }, { value: "safari", labelKey: "browserSafari" }, { value: "edge", labelKey: "browserEdge" }],
        syslogFacilities: [{ value: "user", labelKey: "syslogFacilityUser" }, { value: "daemon", labelKey: "syslogFacilityDaemon" }, { value: "local0", labelKey: "syslogFacilityLocal0" }],
        syslogSeverities: [{ value: "info", labelKey: "syslogSeverityInfo" }, { value: "notice", labelKey: "syslogSeverityNotice" }, { value: "warning", labelKey: "syslogSeverityWarning" }]
    };

    var FIELD_DEFS = {
        host: { type: "text", labelKey: "hostLabel", placeholder: "google.com", spellcheck: false },
        path: { type: "text", labelKey: "pathLabel", placeholder: "/", defaultValue: "/", spellcheck: false },
        httpMethod: { type: "select", labelKey: "methodLabel", optionSet: "httpMethods", defaultValue: "GET" },
        sipAction: { type: "select", labelKey: "actionLabel", optionSet: "sipActions", defaultValue: "OPTIONS" },
        coapMethod: { type: "select", labelKey: "methodLabel", optionSet: "coapMethods", defaultValue: "GET" },
        randomQuery: { type: "checkbox", labelKey: "randomQueryLabel", defaultValue: true },
        filename: { type: "text", labelKey: "filenameLabel", defaultValue: "test.bin", spellcheck: false },
        username: { type: "text", labelKey: "usernameLabel", spellcheck: false },
        database: { type: "text", labelKey: "databaseLabel", spellcheck: false },
        community: { type: "text", labelKey: "communityLabel", defaultValue: "public", spellcheck: false },
        oid: { type: "text", labelKey: "oidLabel", defaultValue: "1.3.6.1.2.1.1.1.0", spellcheck: false },
        message: { type: "textarea", labelKey: "messageLabel", defaultValue: "payloadgen test", className: "field field-wide", rows: 3, spellcheck: false },
        clientId: { type: "text", labelKey: "clientIdLabel", spellcheck: false },
        tlsAlpn: { type: "select", labelKey: "alpnLabel", optionSet: "tlsAlpn", defaultValue: "h2" },
        quicVersion: { type: "select", labelKey: "quicVersionLabel", optionSet: "quicVersions", defaultValue: "v1" },
        quicAwgSegmented: { type: "checkbox", labelKey: "quicAwgSegmentedLabel", defaultValue: false },
        quicAwgLevel: { type: "select", labelKey: "quicAwgLevelLabel", optionSet: "quicAwgLevels", defaultValue: "0" },
        browserProfile: { type: "select", labelKey: "browserLabel", optionSet: "browserProfiles", defaultValue: "chrome" },
        browserVersion: { type: "text", labelKey: "browserVersionLabel", placeholder: "auto", spellcheck: false },
        syslogFacility: { type: "select", labelKey: "facilityLabel", optionSet: "syslogFacilities", defaultValue: "user" },
        syslogSeverity: { type: "select", labelKey: "severityLabel", optionSet: "syslogSeverities", defaultValue: "info" },
        quicEncrypt: { type: "checkbox", labelKey: "quicEncryptLabel", defaultValue: true }
    };

    var PROTOCOL_CATALOG = [
        { id: "dns", categoryId: "discovery", transport: "udp", port: 53, rank: 1, labelKey: "protocolDns", descriptorKey: "descDns", fieldSet: ["host"] },
        { id: "mdns", categoryId: "discovery", transport: "udp", port: 5353, rank: 2, labelKey: "protocolMdns", descriptorKey: "descMdns", fieldSet: ["host"] },
        { id: "ssdp", categoryId: "discovery", transport: "udp", port: 1900, rank: 3, labelKey: "protocolSsdp", descriptorKey: "descSsdp", fieldSet: [] },
        { id: "llmnr", categoryId: "discovery", transport: "udp", port: 5355, rank: 4, labelKey: "protocolLlmnr", descriptorKey: "descLlmnr", fieldSet: ["host"] },
        { id: "nbns", categoryId: "discovery", transport: "udp", port: 137, rank: 5, labelKey: "protocolNbns", descriptorKey: "descNbns", fieldSet: ["host"] },
        { id: "quic", categoryId: "web", transport: "udp", port: 443, rank: 1, labelKey: "protocolQuic", descriptorKey: "descQuic", fieldSet: ["host", "browserProfile", "quicVersion", "quicEncrypt", "quicAwgSegmented", "quicAwgLevel"], defaults: { browserProfile: "chrome", quicVersion: "v1", quicEncrypt: true, quicAwgSegmented: false, quicAwgLevel: "0" } },
        { id: "tls_client_hello", categoryId: "web", transport: "tcp", port: 443, rank: 2, labelKey: "protocolTlsClientHello", descriptorKey: "descTlsClientHello", fieldSet: ["host", "browserProfile", "browserVersion", "tlsAlpn"], defaults: { tlsAlpn: "h2", browserProfile: "chrome" } },
        { id: "http2", categoryId: "web", transport: "tcp", port: 80, rank: 3, labelKey: "protocolHttp2", descriptorKey: "descHttp2", fieldSet: ["host", "path", "browserProfile", "browserVersion"], defaults: { path: "/", browserProfile: "chrome" } },
        { id: "http_browser", categoryId: "web", transport: "tcp", port: 80, rank: 4, labelKey: "protocolHttpBrowser", descriptorKey: "descHttpBrowser", fieldSet: ["host", "browserProfile", "browserVersion", "path", "randomQuery"], defaults: { path: "/", randomQuery: true, browserProfile: "chrome" } },
        { id: "websocket", categoryId: "web", transport: "tcp", port: 80, rank: 5, labelKey: "protocolWebsocket", descriptorKey: "descWebsocket", fieldSet: ["host", "browserProfile", "browserVersion", "path"], defaults: { path: "/", browserProfile: "chrome" } },
        { id: "curl", categoryId: "web", transport: "tcp", port: 80, rank: 6, labelKey: "protocolCurl", descriptorKey: "descCurl", fieldSet: ["host", "path", "httpMethod", "randomQuery"], defaults: { path: "/", httpMethod: "GET", randomQuery: true } },
        { id: "stun", categoryId: "realtime", transport: "udp", port: 3478, rank: 1, labelKey: "protocolStun", descriptorKey: "descStun", fieldSet: ["host"] },
        { id: "dtls", categoryId: "realtime", transport: "udp", port: 443, rank: 2, labelKey: "protocolDtls", descriptorKey: "descDtls", fieldSet: ["host"] },
        { id: "sip", categoryId: "realtime", transport: "udp", port: 5060, rank: 3, labelKey: "protocolSip", descriptorKey: "descSip", fieldSet: ["host", "sipAction"], defaults: { sipAction: "OPTIONS" } },
        { id: "rtp", categoryId: "realtime", transport: "udp", port: 5004, rank: 4, labelKey: "protocolRtp", descriptorKey: "descRtp", fieldSet: [] },
        { id: "rtcp", categoryId: "realtime", transport: "udp", port: 5005, rank: 5, labelKey: "protocolRtcp", descriptorKey: "descRtcp", fieldSet: [] },
        { id: "coap", categoryId: "iot", transport: "udp", port: 5683, rank: 1, labelKey: "protocolCoap", descriptorKey: "descCoap", fieldSet: ["host", "path", "coapMethod"], defaults: { path: "/", coapMethod: "GET" } },
        { id: "mqtt", categoryId: "iot", transport: "tcp", port: 1883, rank: 2, labelKey: "protocolMqtt", descriptorKey: "descMqtt", fieldSet: ["clientId"] },
        { id: "ntp", categoryId: "infra", transport: "udp", port: 123, rank: 1, labelKey: "protocolNtp", descriptorKey: "descNtp", fieldSet: [] },
        { id: "dhcp_discover", categoryId: "infra", transport: "udp", port: 67, rank: 2, labelKey: "protocolDhcpDiscover", descriptorKey: "descDhcpDiscover", fieldSet: [] },
        { id: "snmp", categoryId: "infra", transport: "udp", port: 161, rank: 3, labelKey: "protocolSnmp", descriptorKey: "descSnmp", fieldSet: ["community", "oid"], defaults: { community: "public", oid: "1.3.6.1.2.1.1.1.0" } },
        { id: "syslog", categoryId: "infra", transport: "udp", port: 514, rank: 4, labelKey: "protocolSyslog", descriptorKey: "descSyslog", fieldSet: ["message", "syslogFacility", "syslogSeverity"], defaults: { message: "payloadgen test", syslogFacility: "user", syslogSeverity: "info" } },
        { id: "tftp", categoryId: "infra", transport: "udp", port: 69, rank: 5, labelKey: "protocolTftp", descriptorKey: "descTftp", fieldSet: ["filename"], defaults: { filename: "test.bin" } },
        { id: "radius", categoryId: "infra", transport: "udp", port: 1812, rank: 6, labelKey: "protocolRadius", descriptorKey: "descRadius", fieldSet: ["username"], defaults: { username: "user" } },
        { id: "redis", categoryId: "messaging", transport: "tcp", port: 6379, rank: 1, labelKey: "protocolRedis", descriptorKey: "descRedis", fieldSet: [] },
        { id: "postgresql", categoryId: "messaging", transport: "tcp", port: 5432, rank: 2, labelKey: "protocolPostgresql", descriptorKey: "descPostgresql", fieldSet: ["username", "database"], defaults: { username: "postgres", database: "postgres" } },
        { id: "mysql", categoryId: "messaging", transport: "tcp", port: 3306, rank: 3, labelKey: "protocolMysql", descriptorKey: "descMysql", fieldSet: ["username"], defaults: { username: "root" } },
        { id: "utp", categoryId: "p2p", transport: "udp", port: 6881, rank: 1, labelKey: "protocolUtp", descriptorKey: "descUtp", fieldSet: [] },
        { id: "bittorrent_dht", categoryId: "p2p", transport: "udp", port: 6881, rank: 2, labelKey: "protocolBittorrentDht", descriptorKey: "descBittorrentDht", fieldSet: [] }
    ];

    var POPULAR_PROTOCOL_IDS = ["dns", "quic", "tls_client_hello", "http_browser", "stun", "http2"];
    var PROTOCOL_WIKI_URLS = {
        en: { dns: "https://en.wikipedia.org/wiki/Domain_Name_System", mdns: "https://en.wikipedia.org/wiki/Multicast_DNS", ssdp: "https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol", llmnr: "https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution", nbns: "https://en.wikipedia.org/wiki/NetBIOS_over_TCP/IP", quic: "https://en.wikipedia.org/wiki/QUIC", tls_client_hello: "https://en.wikipedia.org/wiki/Transport_Layer_Security", http2: "https://en.wikipedia.org/wiki/HTTP/2", http_browser: "https://en.wikipedia.org/wiki/HTTP", websocket: "https://en.wikipedia.org/wiki/WebSocket", curl: "https://en.wikipedia.org/wiki/CURL", stun: "https://en.wikipedia.org/wiki/STUN", dtls: "https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security", sip: "https://en.wikipedia.org/wiki/Session_Initiation_Protocol", rtp: "https://en.wikipedia.org/wiki/Real-time_Transport_Protocol", rtcp: "https://en.wikipedia.org/wiki/RTP_Control_Protocol", coap: "https://en.wikipedia.org/wiki/Constrained_Application_Protocol", mqtt: "https://en.wikipedia.org/wiki/MQTT", ntp: "https://en.wikipedia.org/wiki/Network_Time_Protocol", dhcp_discover: "https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol", snmp: "https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol", syslog: "https://en.wikipedia.org/wiki/Syslog", tftp: "https://en.wikipedia.org/wiki/Trivial_File_Transfer_Protocol", radius: "https://en.wikipedia.org/wiki/RADIUS", redis: "https://en.wikipedia.org/wiki/Redis", postgresql: "https://en.wikipedia.org/wiki/PostgreSQL", mysql: "https://en.wikipedia.org/wiki/MySQL", utp: "https://en.wikipedia.org/wiki/Micro_Transport_Protocol", bittorrent_dht: "https://en.wikipedia.org/wiki/Mainline_DHT" },
        ru: { dns: "https://ru.wikipedia.org/wiki/DNS", mdns: "https://ru.wikipedia.org/wiki/Multicast_DNS", ssdp: "https://ru.wikipedia.org/wiki/Simple_Service_Discovery_Protocol", llmnr: "https://ru.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution", nbns: "https://ru.wikipedia.org/wiki/NetBIOS_over_TCP/IP", quic: "https://ru.wikipedia.org/wiki/QUIC", tls_client_hello: "https://ru.wikipedia.org/wiki/TLS", http2: "https://ru.wikipedia.org/wiki/HTTP/2", http_browser: "https://ru.wikipedia.org/wiki/HTTP", websocket: "https://ru.wikipedia.org/wiki/WebSocket", curl: "https://ru.wikipedia.org/wiki/CURL", stun: "https://ru.wikipedia.org/wiki/STUN", dtls: "https://ru.wikipedia.org/wiki/Datagram_Transport_Layer_Security", sip: "https://ru.wikipedia.org/wiki/Session_Initiation_Protocol", rtp: "https://ru.wikipedia.org/wiki/RTP", rtcp: "https://ru.wikipedia.org/wiki/RTCP", coap: "https://ru.wikipedia.org/wiki/Constrained_Application_Protocol", mqtt: "https://ru.wikipedia.org/wiki/MQTT", ntp: "https://ru.wikipedia.org/wiki/Network_Time_Protocol", dhcp_discover: "https://ru.wikipedia.org/wiki/DHCP", snmp: "https://ru.wikipedia.org/wiki/SNMP", syslog: "https://ru.wikipedia.org/wiki/Syslog", tftp: "https://ru.wikipedia.org/wiki/TFTP", radius: "https://ru.wikipedia.org/wiki/RADIUS", redis: "https://ru.wikipedia.org/wiki/Redis", postgresql: "https://ru.wikipedia.org/wiki/PostgreSQL", mysql: "https://ru.wikipedia.org/wiki/MySQL", utp: "https://ru.wikipedia.org/wiki/Micro_Transport_Protocol", bittorrent_dht: "https://ru.wikipedia.org/wiki/Mainline_DHT" }
    };
    var SSDP_SEARCH_TARGETS = ["ssdp:all", "upnp:rootdevice", "urn:schemas-upnp-org:device:InternetGatewayDevice:1", "urn:schemas-upnp-org:service:WANIPConnection:1", "urn:schemas-upnp-org:device:MediaServer:1"];
    var BROWSER_USER_AGENTS = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.7680.154 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Safari/605.1.15",
        "Mozilla/5.0 (X11; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0"
    ];
    var CURL_USER_AGENTS = ["curl/8.4.0", "curl/8.5.0", "curl/8.7.1", "curl/8.9.1"];
    var BROWSER_PROFILES = {
        chrome: { defaultVersion: "146.0.7680.154", tlsStyle: "chromium" },
        firefox: { defaultVersion: "149.0", tlsStyle: "firefox" },
        safari: { defaultVersion: "26.4", tlsStyle: "safari" },
        edge: { defaultVersion: "146.0.3856.84", tlsStyle: "edge" }
    };

    // Static popularity snapshots prepared on 2026-04-01 from ahrefstop.com
    // and filtered against the publicly mirrored zapret-info/z-i dump snapshot.
    var DOMAIN_SNAPSHOTS = {
        global: [
            "wikipedia.org", "chatgpt.com", "google.com", "reddit.com", "whatsapp.com", "pinterest.com", "apple.com", "amazon.com", "tiktok.com", "imdb.com",
            "x.com", "microsoft.com", "yahoo.com", "globo.com", "nytimes.com", "fandom.com", "yahoo.co.jp", "mayoclinic.org", "ilovepdf.com", "netflix.com",
            "clevelandclinic.org", "openai.com", "spotify.com", "roblox.com", "espn.com", "bbc.co.uk", "adobe.com", "indeed.com", "amazon.in", "cricbuzz.com",
            "espncricinfo.com", "nih.gov", "ikea.com", "poki.com", "investing.com", "flipkart.com", "yelp.com", "rakuten.co.jp", "scribd.com", "amazon.de",
            "trendyol.com", "uol.com.br", "samsung.com", "steampowered.com", "nhs.uk", "mercadolivre.com.br", "accuweather.com", "booking.com", "wise.com", "amazon.co.uk",
            "gov.uk", "live.com", "amazon.co.jp", "tripadvisor.com", "medlineplus.gov", "detik.com", "merriam-webster.com", "tradingview.com", "alodokter.com", "walmart.com",
            "freepik.com", "hurriyet.com.tr", "cookpad.com", "savefrom.net", "yandex.com.tr", "auburn.edu", "namu.wiki", "primevideo.com", "ebay.com", "smallpdf.com",
            "sahibinden.com", "365scores.com", "discord.com", "1mg.com", "nike.com", "healthline.com", "rottentomatoes.com", "weather.com", "shopee.co.id", "yandex.ru",
            "speedtest.net", "etsy.com", "epfindia.gov.in", "thethaovanhoa.vn", "icc-cricket.com", "tff.org", "wayground.com", "nta.go.jp", "saude.gov.br", "formula1.com",
            "perplexity.ai", "todamateria.com.br", "borsaitaliana.it", "livemint.com", "telangana.gov.in", "estadao.com.br", "pro-football-reference.com", "turkiye.gov.tr", "indianexpress.com", "currys.co.uk"
        ],
        ru: [
            "wikipedia.org", "yandex.ru", "ozon.ru", "vk.com", "google.com", "gismeteo.ru", "mail.ru", "kinopoisk.ru", "pinterest.com", "dzen.ru",
            "rutube.ru", "gdz.ru", "apple.com", "rbc.ru", "reddit.com", "wildberries.ru", "asna.ru", "ya.ru", "vidal.ru", "banki.ru",
            "sberbank.ru", "ria.ru", "tbank.ru", "championat.com", "fandom.com", "rambler.ru", "kp.ru", "dns-shop.ru", "russianfood.com", "eapteka.ru",
            "chatgpt.com", "avito.ru", "2gis.ru", "roblox.com", "telegram.org", "cbr.ru", "ivi.ru", "gosuslugi.ru", "yandex.kz", "pozdravok.com",
            "microsoft.com", "kino-teatr.ru", "consultant.ru", "lenta.ru", "auto.ru", "smclinic.ru", "steampowered.com", "funpay.com", "rustore.ru", "okko.tv",
            "domclick.ru", "sports.ru", "t.me", "cian.ru", "drom.ru", "investing.com", "whatsapp.com", "gastronom.ru", "24smi.org", "sravni.ru",
            "tiktok.com", "iamcook.ru", "vseinstrumenti.ru", "planetazdorovo.ru", "wiktionary.org", "soccer365.ru", "aviasales.ru", "proxifier.com", "sovcombank.ru", "irecommend.ru",
            "sportbox.ru", "freepik.com", "gemotest.ru", "invitro.ru", "github.com", "tutu.ru", "skysmart.ru", "vtb.ru", "goldapple.ru", "ok.ru",
            "kareliameteo.ru", "pikabu.ru", "deepl.com", "meteoinfo.ru", "tripadvisor.ru", "iz.ru", "megapteka.ru", "apteka.ru", "reverso.net", "hh.ru",
            "primpogoda.ru", "habr.com", "gdz-raketa.ru", "uchi.ru", "lamoda.ru", "deti-online.com", "promokodi.net", "gorzdrav.org", "uiscom.ru", "primbank.ru"
        ]
    };
    var LOCALES = {
        en: {
            documentTitle: "PayloadGen",
            pageDescription: "Categorized protocol payload generator.",
            pageTitle: "PayloadGen",
            pageIntroHtml: "Generate <code>i1..i5</code> payload.",
            localeToggleLabel: "Switch language",
            mtuLabel: "Global MTU",
            padMtuLabel: "Pad to MTU",
            addButton: "Add Payload",
            generateButton: "Generate",
            copyButton: "Copy Output",
            resetButton: "Reset",
            donateButton: "Donate",
            blocksTitle: "Payload Blocks",
            blocksTextHtml: "Add up to five blocks. Generated chunks are flattened into at most five output lines.",
            outputLabel: "Generated Output",
            outputPlaceholder: "Press Generate to build i1..i5 lines.",
            payloadBlockTitle: "Payload",
            protocolLabel: "Protocol",
            hostLabel: "Host / Domain",
            pathLabel: "Path",
            methodLabel: "Method",
            actionLabel: "Action",
            randomQueryLabel: "Random Query",
            filenameLabel: "Filename",
            usernameLabel: "Username",
            databaseLabel: "Database",
            communityLabel: "Community",
            oidLabel: "OID",
            messageLabel: "Message",
            clientIdLabel: "Client ID",
            alpnLabel: "ALPN",
            quicVersionLabel: "QUIC Version",
            quicAwgSegmentedLabel: "AWG Segmented",
            quicAwgLevelLabel: "AWG Level",
            browserLabel: "Browser",
            browserVersionLabel: "Version",
            randomHostButton: "Random",
            randomHostRuLabel: "RU",
            facilityLabel: "Facility",
            severityLabel: "Severity",
            quicEncryptLabel: "Encrypt",
            wikiLinkLabel: "Wiki",
            removeButton: "Remove",
            statusAddedBlock: "Added a new payload block.",
            statusRemovedBlock: "Payload block removed.",
            statusReset: "Reset to a single QUIC payload block.",
            statusReady: "Ready to generate payload lines.",
            statusNoOutput: "No payload output was generated. Check the block errors and try again.",
            statusCappedOutput: "Output stopped at the Android limit of 5 lines.",
            statusCopyEmpty: "Nothing to copy because no payload lines were generated.",
            statusCopyFailed: "Copy failed in this browser context. The output is still available to select manually.",
            statusRandomDomainNoTargets: "This block does not use a host/domain field.",
            rankingGlobal: "global",
            rankingRu: "RU",
            categoryDiscovery: "Discovery & Name Resolution",
            categoryWeb: "Web & Secure Web",
            categoryRealtime: "Realtime & Media",
            categoryIot: "IoT & Device",
            categoryInfra: "Infrastructure & Operations",
            categoryMessaging: "Messaging & Databases",
            categoryP2p: "P2P & Distribution",
            transportUdp: "UDP",
            transportTcp: "TCP",
            httpMethodGet: "GET",
            httpMethodHead: "HEAD",
            httpMethodPost: "POST",
            sipActionOptions: "OPTIONS",
            sipActionRegister: "REGISTER",
            coapMethodGet: "GET",
            coapMethodPost: "POST",
            tlsAlpnHttp11: "http/1.1",
            tlsAlpnH2: "h2",
            quicVersionV1: "QUIC v1",
            quicVersionV2: "QUIC v2",
            quicAwgLevel0: "Level 0",
            quicAwgLevel1: "Level 1",
            quicAwgLevel2: "Level 2",
            quicAwgLevel3: "Level 3",
            quicAwgLevel4: "Level 4",
            browserChrome: "Chrome",
            browserFirefox: "Firefox",
            browserSafari: "Safari",
            browserEdge: "Edge",
            syslogFacilityUser: "user",
            syslogFacilityDaemon: "daemon",
            syslogFacilityLocal0: "local0",
            syslogSeverityInfo: "info",
            syslogSeverityNotice: "notice",
            syslogSeverityWarning: "warning",
            protocolDns: "DNS",
            protocolMdns: "mDNS",
            protocolSsdp: "SSDP",
            protocolLlmnr: "LLMNR",
            protocolNbns: "NBNS",
            protocolQuic: "QUIC (HTTP/3)",
            protocolTlsClientHello: "TLS ClientHello",
            protocolHttp2: "HTTP/2",
            protocolHttpBrowser: "HTTP Browser",
            protocolWebsocket: "WebSocket",
            protocolCurl: "cURL (HTTP/1.1)",
            protocolStun: "STUN",
            protocolDtls: "DTLS (WebRTC)",
            protocolSip: "SIP",
            protocolRtp: "RTP",
            protocolRtcp: "RTCP",
            protocolCoap: "CoAP",
            protocolMqtt: "MQTT",
            protocolNtp: "NTP",
            protocolDhcpDiscover: "DHCP DISCOVER",
            protocolSnmp: "SNMP",
            protocolSyslog: "Syslog",
            protocolTftp: "TFTP",
            protocolRadius: "RADIUS",
            protocolRedis: "Redis RESP",
            protocolPostgresql: "PostgreSQL",
            protocolMysql: "MySQL",
            protocolUtp: "uTP (BitTorrent)",
            protocolBittorrentDht: "BitTorrent DHT",
            descDns: "Standard A-record query",
            descMdns: "Multicast DNS query with randomized query class and DNS case",
            descSsdp: "Generated discovery probe",
            descLlmnr: "LLMNR hostname query",
            descNbns: "NetBIOS name query",
            descQuic: "Initial-like QUIC payload",
            descTlsClientHello: "TLS ClientHello packet",
            descHttp2: "Browser-style HTTP/2 preface, SETTINGS, and opening stream",
            descHttpBrowser: "Browser-style HTTP/1.1 request",
            descWebsocket: "WebSocket upgrade request",
            descCurl: "Dynamic HTTP/1.1 request with curl User-Agent",
            descStun: "Binding Request with SOFTWARE attribute",
            descDtls: "ClientHello-like DTLS datagram",
            descSip: "SIP request with randomized headers",
            descRtp: "12-byte RTP header",
            descRtcp: "Receiver Report-like RTCP packet",
            descCoap: "CoAP request with Uri-Host and Uri-Path",
            descMqtt: "MQTT CONNECT packet",
            descNtp: "NTP v4 client request",
            descDhcpDiscover: "DHCP DISCOVER packet",
            descSnmp: "SNMP GET request",
            descSyslog: "UDP syslog message",
            descTftp: "TFTP RRQ request with negotiated option extensions",
            descRadius: "RADIUS Access-Request",
            descRedis: "RESP PING request",
            descPostgresql: "PostgreSQL startup packet",
            descMysql: "MySQL client command packet",
            descUtp: "20-byte SYN frame",
            descBittorrentDht: "BitTorrent DHT ping query"
        },
        ru: {
            documentTitle: "PayloadGen",
            pageDescription: "Каталоговый генератор protocol payload.",
            pageTitle: "PayloadGen",
            pageIntroHtml: "Генерация <code>i1..i5</code> payload.",
            localeToggleLabel: "Сменить язык",
            mtuLabel: "Глобальный MTU",
            padMtuLabel: "Дополнять до MTU",
            addButton: "Добавить payload",
            generateButton: "Сгенерировать",
            copyButton: "Копировать вывод",
            resetButton: "Сброс",
            donateButton: "Поддержать",
            blocksTitle: "Блоки payload",
            blocksTextHtml: "Можно добавить до пяти блоков. Части автоматически сворачиваются максимум в пять строк вывода.",
            outputLabel: "Сгенерированный вывод",
            outputPlaceholder: "Нажмите Сгенерировать, чтобы собрать строки i1..i5.",
            payloadBlockTitle: "Блок",
            protocolLabel: "Протокол",
            hostLabel: "Хост / Домен",
            pathLabel: "Путь",
            methodLabel: "Метод",
            actionLabel: "Действие",
            randomQueryLabel: "Случайный query",
            filenameLabel: "Имя файла",
            usernameLabel: "Имя пользователя",
            databaseLabel: "База данных",
            communityLabel: "Community",
            oidLabel: "OID",
            messageLabel: "Сообщение",
            clientIdLabel: "Client ID",
            alpnLabel: "ALPN",
            quicVersionLabel: "Версия QUIC",
            quicAwgSegmentedLabel: "AWG-сегменты",
            quicAwgLevelLabel: "Уровень AWG",
            browserLabel: "Браузер",
            browserVersionLabel: "Версия",
            randomHostButton: "Случайный",
            randomHostRuLabel: "RU",
            facilityLabel: "Facility",
            severityLabel: "Severity",
            quicEncryptLabel: "Шифровать",
            wikiLinkLabel: "Вики",
            removeButton: "Удалить",
            statusAddedBlock: "Добавлен новый блок payload.",
            statusRemovedBlock: "Блок payload удалён.",
            statusReset: "Сброшено до одного блока QUIC.",
            statusReady: "Готово к генерации строк payload.",
            statusNoOutput: "Не удалось сгенерировать вывод. Проверьте ошибки в блоках и повторите.",
            statusCappedOutput: "Вывод остановлен на лимите Android в 5 строк.",
            statusCopyEmpty: "Нечего копировать: строки payload не сгенерированы.",
            statusCopyFailed: "Не удалось скопировать в этом контексте браузера. Текст можно выделить вручную.",
            statusRandomDomainNoTargets: "Этот блок не использует поле host/domain.",
            rankingGlobal: "глобального",
            rankingRu: "RU",
            categoryDiscovery: "Обнаружение и имена",
            categoryWeb: "Web и защищённый web",
            categoryRealtime: "Реалтайм и медиа",
            categoryIot: "IoT и устройства",
            categoryInfra: "Инфраструктура и операции",
            categoryMessaging: "Сообщения и базы",
            categoryP2p: "P2P и распространение",
            transportUdp: "UDP",
            transportTcp: "TCP",
            httpMethodGet: "GET",
            httpMethodHead: "HEAD",
            httpMethodPost: "POST",
            sipActionOptions: "OPTIONS",
            sipActionRegister: "REGISTER",
            coapMethodGet: "GET",
            coapMethodPost: "POST",
            tlsAlpnHttp11: "http/1.1",
            tlsAlpnH2: "h2",
            quicVersionV1: "QUIC v1",
            quicVersionV2: "QUIC v2",
            quicAwgLevel0: "Уровень 0",
            quicAwgLevel1: "Уровень 1",
            quicAwgLevel2: "Уровень 2",
            quicAwgLevel3: "Уровень 3",
            quicAwgLevel4: "Уровень 4",
            browserChrome: "Chrome",
            browserFirefox: "Firefox",
            browserSafari: "Safari",
            browserEdge: "Edge",
            syslogFacilityUser: "user",
            syslogFacilityDaemon: "daemon",
            syslogFacilityLocal0: "local0",
            syslogSeverityInfo: "info",
            syslogSeverityNotice: "notice",
            syslogSeverityWarning: "warning",
            protocolDns: "DNS",
            protocolMdns: "mDNS",
            protocolSsdp: "SSDP",
            protocolLlmnr: "LLMNR",
            protocolNbns: "NBNS",
            protocolQuic: "QUIC (HTTP/3)",
            protocolTlsClientHello: "TLS ClientHello",
            protocolHttp2: "HTTP/2",
            protocolHttpBrowser: "HTTP Browser",
            protocolWebsocket: "WebSocket",
            protocolCurl: "cURL (HTTP/1.1)",
            protocolStun: "STUN",
            protocolDtls: "DTLS (WebRTC)",
            protocolSip: "SIP",
            protocolRtp: "RTP",
            protocolRtcp: "RTCP",
            protocolCoap: "CoAP",
            protocolMqtt: "MQTT",
            protocolNtp: "NTP",
            protocolDhcpDiscover: "DHCP DISCOVER",
            protocolSnmp: "SNMP",
            protocolSyslog: "Syslog",
            protocolTftp: "TFTP",
            protocolRadius: "RADIUS",
            protocolRedis: "Redis RESP",
            protocolPostgresql: "PostgreSQL",
            protocolMysql: "MySQL",
            protocolUtp: "uTP (BitTorrent)",
            protocolBittorrentDht: "BitTorrent DHT",
            descDns: "Стандартный A-запрос DNS",
            descMdns: "Multicast DNS запрос со случайным query class и регистром DNS-имени",
            descSsdp: "Генерируемый discovery-запрос",
            descLlmnr: "LLMNR-запрос имени хоста",
            descNbns: "Запрос NetBIOS имени",
            descQuic: "QUIC payload в стиле Initial",
            descTlsClientHello: "Пакет TLS ClientHello",
            descHttp2: "HTTP/2 preface, SETTINGS и стартовый stream в стиле браузера",
            descHttpBrowser: "HTTP/1.1 запрос в стиле браузера",
            descWebsocket: "WebSocket upgrade-запрос",
            descCurl: "Динамический HTTP/1.1 запрос с User-Agent от curl",
            descStun: "Binding Request с атрибутом SOFTWARE",
            descDtls: "DTLS-датаграмма в стиле ClientHello",
            descSip: "SIP-запрос со случайными заголовками",
            descRtp: "12-байтный RTP header",
            descRtcp: "RTCP packet в стиле Receiver Report",
            descCoap: "CoAP-запрос с Uri-Host и Uri-Path",
            descMqtt: "Пакет MQTT CONNECT",
            descNtp: "Клиентский NTP v4 запрос",
            descDhcpDiscover: "Пакет DHCP DISCOVER",
            descSnmp: "SNMP GET запрос",
            descSyslog: "UDP syslog-сообщение",
            descTftp: "TFTP RRQ запрос с negotiated option extensions",
            descRadius: "RADIUS Access-Request",
            descRedis: "RESP PING запрос",
            descPostgresql: "Пакет запуска PostgreSQL",
            descMysql: "Командный пакет клиента MySQL",
            descUtp: "20-байтный SYN-кадр",
            descBittorrentDht: "BitTorrent DHT ping-запрос"
        }
    };

    return {
        CONFIG: CONFIG,
        STORAGE_KEYS: STORAGE_KEYS,
        THEMES: THEMES,
        DONATE_URL: DONATE_URL,
        LATEST_QUIC_VERSION: LATEST_QUIC_VERSION,
        CATEGORY_DEFS: CATEGORY_DEFS,
        OPTION_SETS: OPTION_SETS,
        FIELD_DEFS: FIELD_DEFS,
        PROTOCOL_CATALOG: PROTOCOL_CATALOG,
        POPULAR_PROTOCOL_IDS: POPULAR_PROTOCOL_IDS,
        PROTOCOL_WIKI_URLS: PROTOCOL_WIKI_URLS,
        SSDP_SEARCH_TARGETS: SSDP_SEARCH_TARGETS,
        BROWSER_USER_AGENTS: BROWSER_USER_AGENTS,
        CURL_USER_AGENTS: CURL_USER_AGENTS,
        BROWSER_PROFILES: BROWSER_PROFILES,
        DOMAIN_SNAPSHOTS: DOMAIN_SNAPSHOTS,
        LOCALES: LOCALES
    };
}));
